
clear
use filiou_desfiliou_tratada

capture drop  disp_de_d_fil_ROB disp_de_e_fil_ROB disp_ec_e_fil_ROB disp_ec_c_fil_ROB disp_dc_d_fil_ROB disp_dc_c_fil_ROB disp_de_d_desfil_ROB disp_de_e_desfil_ROB disp_ec_e_desfil_ROB disp_ec_c_desfil_ROB disp_dc_d_desfil_ROB disp_dc_c_desfil_ROB d_dir_esq_ROB d_dir_ctr_ROB d_esq_ctr_ROB d_fil_direita_ROB d_fil_centro_ROB d_fil_esquerda_ROB
* ################################################################################################################################ MAIN RESULTS WITH ROBUSTNESS TESTS ########################
* ################################################################################################################################ MAIN RESULTS WITH ROBUSTNESS TESTS ########################
* ################################################################################################################################ MAIN RESULTS WITH ROBUSTNESS TESTS ########################
* ################################################################################################################################ MAIN RESULTS WITH ROBUSTNESS TESTS ########################
* ################################################################################################################################ MAIN RESULTS WITH ROBUSTNESS TESTS ########################

capture log close
log using Tables7to9.log, replace
capture erase TableResultsDesfil.xml

* DE efeito na esquerda - Table 7 - Top
rdrobust disp_de_e_desfil margem_vit if 	d_dir_esq==1 & (antes_eleicoes==1) , vce(cluster codigo_ibge) p (1) all h (0.121) b (0.198)
outreg2 using TableResultsDesfil, excel label append nonotes title("Table Results")  
rdrobust disp_de_e_desfil margem_vit if 	d_dir_esq==1 & (todas_eleicoes==1) , vce(cluster codigo_ibge)	p (1) all h (0.133) b (0.237)
outreg2 using TableResultsDesfil, excel label append nonotes title("Table Results")  
rdrobust disp_de_e_desfil margem_vit if 	d_dir_esq==1 & (doisanos_eleicoes==1) , vce(cluster codigo_ibge)	p (1) all h (0.135) b (0.247)
outreg2 using TableResultsDesfil, excel label append nonotes title("Table Results")  
rdrobust disp_de_e_desfil margem_vit if 	d_dir_esq==1 & (todas_eleicoes==1)  & reeleito == 1, vce(cluster codigo_ibge)	p (1) all h (0.183) b (0.284)
outreg2 using TableResultsDesfil, excel label append nonotes title("Table Results")  
rdrobust disp_de_e_desfil margem_vit if 	d_dir_esq==1 & (todas_eleicoes==1) , vce(cluster codigo_ibge)	p (2) all h (0.224) b (0.342) 
outreg2 using TableResultsDesfil, excel label append nonotes title("Table Results")  
rdrobust disp_de_e_desfil margem_vit if 	d_dir_esq==1 & (todas_eleicoes==1)  & reeleito == 1, vce(cluster codigo_ibge)	p (2) all h (0.190) b (0.294) 
outreg2 using TableResultsDesfil, excel label append nonotes title("Table Results")  
rdrobust disp_de_e_desfil margem_vit if 	d_dir_esq==1 & (todas_eleicoes==1) , vce(cluster codigo_ibge)	p (1) all h (0.133) b (0.10) 
outreg2 using TableResultsDesfil, excel label append nonotes title("Table Results")  
rdrobust disp_de_e_desfil margem_vit if 	d_dir_esq==1 & (todas_eleicoes==1)  & reeleito == 1, vce(cluster codigo_ibge)	p (1) all h (0.183) b (0.10)   
outreg2 using TableResultsDesfil, excel label append nonotes title("Table Results")  
rdrobust disp_de_e_desfil margem_vit if 	d_dir_esq==1 & (todas_eleicoes==1) , vce(cluster codigo_ibge)	p (1) all h (0.133) b (0.40) 
outreg2 using TableResultsDesfil, excel label append nonotes title("Table Results")  
rdrobust disp_de_e_desfil margem_vit if 	d_dir_esq==1 & (todas_eleicoes==1)  & reeleito == 1, vce(cluster codigo_ibge)	p (1) all h (0.183) b (0.40)   
outreg2 using TableResultsDesfil, excel label append nonotes title("Table Results")  

* DC efeito no centro - Table 7 - Bottom
rdrobust disp_dc_c_desfil margem_vit if 	d_dir_ctr==1 & (antes_eleicoes==1) , vce(cluster codigo_ibge) 	p (1) all h (0.085) b (0.201)
outreg2 using TableResultsDesfil, excel label append nonotes title("Table Results")  
rdrobust disp_dc_c_desfil margem_vit if 	d_dir_ctr==1 & (todas_eleicoes==1) , vce(cluster codigo_ibge) 	p (1) all h (0.155) b (0.257)
outreg2 using TableResultsDesfil, excel label append nonotes title("Table Results")  
rdrobust disp_dc_c_desfil margem_vit if 	d_dir_ctr==1 & (doisanos_eleicoes==1) , vce(cluster codigo_ibge) 	p (1) all h (0.103) b (0.195)
outreg2 using TableResultsDesfil, excel label append nonotes title("Table Results")  
rdrobust disp_dc_c_desfil margem_vit if 	d_dir_ctr==1 & (todas_eleicoes==1)  & reeleito == 1, vce(cluster codigo_ibge) 	p (1) all h (0.237) b (0.360)
outreg2 using TableResultsDesfil, excel label append nonotes title("Table Results")  
rdrobust disp_dc_c_desfil margem_vit if 	d_dir_ctr==1 & (todas_eleicoes==1) , vce(cluster codigo_ibge)	p (2) all h (0.214) b (0.354) 
outreg2 using TableResultsDesfil, excel label append nonotes title("Table Results")  
rdrobust disp_dc_c_desfil margem_vit if 	d_dir_ctr==1 & (todas_eleicoes==1)  & reeleito == 1, vce(cluster codigo_ibge)	p (2) all h (0.282) b (0.406) 
outreg2 using TableResultsDesfil, excel label append nonotes title("Table Results")  
rdrobust disp_dc_c_desfil margem_vit if 	d_dir_ctr==1 & (todas_eleicoes==1) , vce(cluster codigo_ibge)	p (1) all h (0.155) b (0.10) 
outreg2 using TableResultsDesfil, excel label append nonotes title("Table Results")  
rdrobust disp_dc_c_desfil margem_vit if 	d_dir_ctr==1 & (todas_eleicoes==1)  & reeleito == 1, vce(cluster codigo_ibge)	p (1) all h (0.237) b (0.10)   
outreg2 using TableResultsDesfil, excel label append nonotes title("Table Results")  
rdrobust disp_dc_c_desfil margem_vit if 	d_dir_ctr==1 & (todas_eleicoes==1) , vce(cluster codigo_ibge)	p (1) all h (0.155) b (0.40) 
outreg2 using TableResultsDesfil, excel label append nonotes title("Table Results")  
rdrobust disp_dc_c_desfil margem_vit if 	d_dir_ctr==1 & (todas_eleicoes==1)  & reeleito == 1, vce(cluster codigo_ibge)	p (1) all h (0.237) b (0.40)   
outreg2 using TableResultsDesfil, excel label append nonotes title("Table Results") 

* DE efeito na direita - Table 8 - Top
rdrobust disp_de_d_desfil margem_vit if 	d_dir_esq==1 & (antes_eleicoes==1) , vce(cluster codigo_ibge) p (1) all h (0.112) b (0.171)
outreg2 using TableResultsDesfil, excel label append nonotes title("Table Results")  
rdrobust disp_de_d_desfil margem_vit if 	d_dir_esq==1 & (todas_eleicoes==1) , vce(cluster codigo_ibge)	p (1) all h (0.121) b (0.244)
outreg2 using TableResultsDesfil, excel label append nonotes title("Table Results")  
rdrobust disp_de_d_desfil margem_vit if 	d_dir_esq==1 & (doisanos_eleicoes==1) , vce(cluster codigo_ibge)	p (1) all h (0.128) b (0.227)
outreg2 using TableResultsDesfil, excel label append nonotes title("Table Results")  
rdrobust disp_de_d_desfil margem_vit if 	d_dir_esq==1 & (todas_eleicoes==1)  & reeleito == 1, vce(cluster codigo_ibge)	p (1) all h (0.225) b (0.458)
outreg2 using TableResultsDesfil, excel label append nonotes title("Table Results")  
rdrobust disp_de_d_desfil margem_vit if 	d_dir_esq==1 & (todas_eleicoes==1) , vce(cluster codigo_ibge)	p (2) all h (0.185) b (0.284) 
outreg2 using TableResultsDesfil, excel label append nonotes title("Table Results")
rdrobust disp_de_d_desfil margem_vit if 	d_dir_esq==1 & (todas_eleicoes==1)  & reeleito == 1, vce(cluster codigo_ibge)	p (2) all h (0.244) b (0.355) 
outreg2 using TableResultsDesfil, excel label append nonotes title("Table Results")  
rdrobust disp_de_d_desfil margem_vit if 	d_dir_esq==1 & (todas_eleicoes==1) , vce(cluster codigo_ibge)	p (1) all h (0.121) b (0.10) 
outreg2 using TableResultsDesfil, excel label append nonotes title("Table Results")  
rdrobust disp_de_d_desfil margem_vit if 	d_dir_esq==1 & (todas_eleicoes==1)  & reeleito == 1, vce(cluster codigo_ibge)	p (1) all h (0.225) b (0.10)   
outreg2 using TableResultsDesfil, excel label append nonotes title("Table Results")  
rdrobust disp_de_d_desfil margem_vit if 	d_dir_esq==1 & (todas_eleicoes==1) , vce(cluster codigo_ibge)	p (1) all h (0.121) b (0.40) 
outreg2 using TableResultsDesfil, excel label append nonotes title("Table Results")  
rdrobust disp_de_d_desfil margem_vit if 	d_dir_esq==1 & (todas_eleicoes==1)  & reeleito == 1, vce(cluster codigo_ibge)	p (1) all h (0.225) b (0.40)   
outreg2 using TableResultsDesfil, excel label append nonotes title("Table Results")  

* EC efeito no centro - Table 8 - Bottom
rdrobust disp_ec_c_desfil margem_vit if 	d_esq_ctr==1 & (antes_eleicoes==1) , vce(cluster codigo_ibge) 	p (1) all h (0.112) b (0.207)
outreg2 using TableResultsDesfil, excel label append nonotes title("Table Results")  
rdrobust disp_ec_c_desfil margem_vit if 	d_esq_ctr==1 & (todas_eleicoes==1) , vce(cluster codigo_ibge) p (1) all h (0.143) b (0.228)
outreg2 using TableResultsDesfil, excel label append nonotes title("Table Results")  
rdrobust disp_ec_c_desfil margem_vit if 	d_esq_ctr==1 & (doisanos_eleicoes==1) , vce(cluster codigo_ibge) p (1) all h (0.090) b (0.192)
outreg2 using TableResultsDesfil, excel label append nonotes title("Table Results")  
rdrobust disp_ec_c_desfil margem_vit if 	d_esq_ctr==1 & (todas_eleicoes==1)  & reeleito == 1, vce(cluster codigo_ibge) p (1) all h (0.223) b (0.341)
outreg2 using TableResultsDesfil, excel label append nonotes title("Table Results")  
rdrobust disp_ec_c_desfil margem_vit if 	d_esq_ctr==1 & (todas_eleicoes==1) , vce(cluster codigo_ibge)	p (2) all h (0.216) b (0.291) 
outreg2 using TableResultsDesfil, excel label append nonotes title("Table Results")  
rdrobust disp_ec_c_desfil margem_vit if 	d_esq_ctr==1 & (todas_eleicoes==1)  & reeleito == 1, vce(cluster codigo_ibge)	p (2) all h (0.329) b (0.471) 
outreg2 using TableResultsDesfil, excel label append nonotes title("Table Results")  
rdrobust disp_ec_c_desfil margem_vit if 	d_esq_ctr==1 & (todas_eleicoes==1) , vce(cluster codigo_ibge)	p (1) all h (0.143) b (0.10) 
outreg2 using TableResultsDesfil, excel label append nonotes title("Table Results")  
rdrobust disp_ec_c_desfil margem_vit if 	d_esq_ctr==1 & (todas_eleicoes==1)  & reeleito == 1, vce(cluster codigo_ibge)	p (1) all h (0.223) b (0.10) 
outreg2 using TableResultsDesfil, excel label append nonotes title("Table Results")  
rdrobust disp_ec_c_desfil margem_vit if 	d_esq_ctr==1 & (todas_eleicoes==1) , vce(cluster codigo_ibge)	p (1) all h (0.143) b (0.40) 
outreg2 using TableResultsDesfil, excel label append nonotes title("Table Results")  
rdrobust disp_ec_c_desfil margem_vit if 	d_esq_ctr==1 & (todas_eleicoes==1)  & reeleito == 1, vce(cluster codigo_ibge)	p (1) all h (0.223) b (0.40) 
outreg2 using TableResultsDesfil, excel label append nonotes title("Table Results")  

* DC efeito na direita - Table 9 - Top
rdrobust disp_dc_d_desfil margem_vit if 	d_dir_ctr==1 & (antes_eleicoes==1) , vce(cluster codigo_ibge) 	p (1) all h (0.110) b (0.203)
outreg2 using TableResultsDesfil, excel label append nonotes title("Table Results")  
rdrobust disp_dc_d_desfil margem_vit if 	d_dir_ctr==1 & (todas_eleicoes==1) , vce(cluster codigo_ibge) 	p (1) all h (0.139) b (0.246)
outreg2 using TableResultsDesfil, excel label append nonotes title("Table Results")  
rdrobust disp_dc_d_desfil margem_vit if 	d_dir_ctr==1 & (doisanos_eleicoes==1) , vce(cluster codigo_ibge) 	p (1) all h (0.138) b (0.243)
outreg2 using TableResultsDesfil, excel label append nonotes title("Table Results")  
rdrobust disp_dc_d_desfil margem_vit if 	d_dir_ctr==1 & (todas_eleicoes==1)  & reeleito == 1, vce(cluster codigo_ibge) 	p (1) all h (0.154) b (0.282)
outreg2 using TableResultsDesfil, excel label append nonotes title("Table Results")  
rdrobust disp_dc_d_desfil margem_vit if 	d_dir_ctr==1 & (todas_eleicoes==1) , vce(cluster codigo_ibge)	p (2) all h (0.168) b (0.273) 
outreg2 using TableResultsDesfil, excel label append nonotes title("Table Results")  
rdrobust disp_dc_d_desfil margem_vit if 	d_dir_ctr==1 & (todas_eleicoes==1)  & reeleito == 1, vce(cluster codigo_ibge)	p (2) all h (0.286) b (0.484) 
outreg2 using TableResultsDesfil, excel label append nonotes title("Table Results")  
rdrobust disp_dc_d_desfil margem_vit if 	d_dir_ctr==1 & (todas_eleicoes==1) , vce(cluster codigo_ibge)	p (1) all h (0.139) b (0.10) 
outreg2 using TableResultsDesfil, excel label append nonotes title("Table Results")  
rdrobust disp_dc_d_desfil margem_vit if 	d_dir_ctr==1 & (todas_eleicoes==1)  & reeleito == 1, vce(cluster codigo_ibge)	p (1) all h (0.154) b (0.10)   
outreg2 using TableResultsDesfil, excel label append nonotes title("Table Results")  
rdrobust disp_dc_d_desfil margem_vit if 	d_dir_ctr==1 & (todas_eleicoes==1) , vce(cluster codigo_ibge)	p (1) all h (0.139) b (0.40) 
outreg2 using TableResultsDesfil, excel label append nonotes title("Table Results")  
rdrobust disp_dc_d_desfil margem_vit if 	d_dir_ctr==1 & (todas_eleicoes==1)  & reeleito == 1, vce(cluster codigo_ibge)	p (1) all h (0.154) b (0.40)   
outreg2 using TableResultsDesfil, excel label append nonotes title("Table Results") 

* EC efeito na esquerda - Table 9 - Bottom
rdrobust disp_ec_e_desfil margem_vit if 	d_esq_ctr==1 & (antes_eleicoes==1) , vce(cluster codigo_ibge) 	p (1) all h (0.143) b (0.266)
outreg2 using TableResultsDesfil, excel label append nonotes title("Table Results")  
rdrobust disp_ec_e_desfil margem_vit if 	d_esq_ctr==1 & (todas_eleicoes==1) , vce(cluster codigo_ibge) p (1) all h (0.117) b (0.201)
outreg2 using TableResultsDesfil, excel label append nonotes title("Table Results")  
rdrobust disp_ec_e_desfil margem_vit if 	d_esq_ctr==1 & (doisanos_eleicoes==1) , vce(cluster codigo_ibge) p (1) all h (0.121) b (0.214)
outreg2 using TableResultsDesfil, excel label append nonotes title("Table Results")  
rdrobust disp_ec_e_desfil margem_vit if 	d_esq_ctr==1 & (todas_eleicoes==1)  & reeleito == 1, vce(cluster codigo_ibge) p (1) all h (0.135) b (0.223)
outreg2 using TableResultsDesfil, excel label append nonotes title("Table Results")  
rdrobust disp_ec_e_desfil margem_vit if 	d_esq_ctr==1 & (todas_eleicoes==1) , vce(cluster codigo_ibge)	p (2) all h (0.168) b (0.263) 
outreg2 using TableResultsDesfil, excel label append nonotes title("Table Results")  
rdrobust disp_ec_e_desfil margem_vit if 	d_esq_ctr==1 & (todas_eleicoes==1)  & reeleito == 1, vce(cluster codigo_ibge)	p (2) all h (0.227) b (0.330) 
outreg2 using TableResultsDesfil, excel label append nonotes title("Table Results")  
rdrobust disp_ec_e_desfil margem_vit if 	d_esq_ctr==1 & (todas_eleicoes==1) , vce(cluster codigo_ibge)	p (1) all h (0.117) b (0.10) 
outreg2 using TableResultsDesfil, excel label append nonotes title("Table Results")  
rdrobust disp_ec_e_desfil margem_vit if 	d_esq_ctr==1 & (todas_eleicoes==1)  & reeleito == 1, vce(cluster codigo_ibge)	p (1) all h (0.135) b (0.10) 
outreg2 using TableResultsDesfil, excel label append nonotes title("Table Results")  
rdrobust disp_ec_e_desfil margem_vit if 	d_esq_ctr==1 & (todas_eleicoes==1) , vce(cluster codigo_ibge)	p (1) all h (0.117) b (0.40) 
outreg2 using TableResultsDesfil, excel label append nonotes title("Table Results")  
rdrobust disp_ec_e_desfil margem_vit if 	d_esq_ctr==1 & (todas_eleicoes==1)  & reeleito == 1, vce(cluster codigo_ibge)	p (1) all h (0.135) b (0.40) 
outreg2 using TableResultsDesfil, excel label append nonotes title("Table Results")  

capture log close