
clear
use filiou_desfiliou_tratada

capture drop  d_dir_esq d_dir_ctr d_esq_ctr d_fil_direita d_fil_centro d_fil_esquerda disp_de_d_fil disp_de_e_fil disp_ec_e_fil disp_ec_c_fil disp_dc_d_fil disp_dc_c_fil disp_de_d_desfil disp_de_e_desfil disp_ec_e_desfil disp_ec_c_desfil disp_dc_d_desfil disp_dc_c_desfil
* ################################################################################################################################ PSDB AS A CENTER PARTY ####################################
* ################################################################################################################################ PSDB AS A CENTER PARTY ####################################
* ################################################################################################################################ PSDB AS A CENTER PARTY ####################################
* ################################################################################################################################ PSDB AS A CENTER PARTY ####################################
* ################################################################################################################################ PSDB AS A CENTER PARTY ####################################

capture log close
log using TablesA3toA5.log, replace
capture erase TablePSDBAfil.xml

* DE efeito na direita - Table A.3 - Top
rdrobust disp_de_d_fil_ROB margem_vit if 	d_dir_esq_ROB==1 & (antes_eleicoes==1) , vce(cluster codigo_ibge) p (1) all h (0.115) b (0.200)
outreg2 using TablePSDBAfil, excel label append nonotes title("Table PSDB")  
rdrobust disp_de_d_fil_ROB margem_vit if 	d_dir_esq_ROB==1 & (todas_eleicoes==1) , vce(cluster codigo_ibge)	p (1) all h (0.166) b (0.291)
outreg2 using TablePSDBAfil, excel label append nonotes title("Table PSDB")  
rdrobust disp_de_d_fil_ROB margem_vit if 	d_dir_esq_ROB==1 & (doisanos_eleicoes==1) , vce(cluster codigo_ibge)	p (1) all h (0.159) b (0.311)
outreg2 using TablePSDBAfil, excel label append nonotes title("Table PSDB")  
rdrobust disp_de_d_fil_ROB margem_vit if 	d_dir_esq_ROB==1 & (todas_eleicoes==1)  & reeleito == 1, vce(cluster codigo_ibge)	p (1) all h (0.232) b (0.387)
outreg2 using TablePSDBAfil, excel label append nonotes title("Table PSDB")  
rdrobust disp_de_d_fil_ROB margem_vit if 	d_dir_esq_ROB==1 & (todas_eleicoes==1) , vce(cluster codigo_ibge)	p (2) all h (0.306) b (0.501) 
outreg2 using TablePSDBAfil, excel label append nonotes title("Table PSDB")
rdrobust disp_de_d_fil_ROB margem_vit if 	d_dir_esq_ROB==1 & (todas_eleicoes==1)  & reeleito == 1, vce(cluster codigo_ibge)	p (2) all h (0.228) b (0.328) 
outreg2 using TablePSDBAfil, excel label append nonotes title("Table PSDB")  
rdrobust disp_de_d_fil_ROB margem_vit if 	d_dir_esq_ROB==1 & (todas_eleicoes==1) , vce(cluster codigo_ibge)	p (1) all h (0.166) b (0.10) 
outreg2 using TablePSDBAfil, excel label append nonotes title("Table PSDB")  
rdrobust disp_de_d_fil_ROB margem_vit if 	d_dir_esq_ROB==1 & (todas_eleicoes==1)  & reeleito == 1, vce(cluster codigo_ibge)	p (1) all h (0.232) b (0.10)  
outreg2 using TablePSDBAfil, excel label append nonotes title("Table PSDB")  
rdrobust disp_de_d_fil_ROB margem_vit if 	d_dir_esq_ROB==1 & (todas_eleicoes==1) , vce(cluster codigo_ibge)	p (1) all h (0.166) b (0.40) 
outreg2 using TablePSDBAfil, excel label append nonotes title("Table PSDB")  
rdrobust disp_de_d_fil_ROB margem_vit if 	d_dir_esq_ROB==1 & (todas_eleicoes==1)  & reeleito == 1, vce(cluster codigo_ibge)	p (1) all h (0.232) b (0.40)  
outreg2 using TablePSDBAfil, excel label append nonotes title("Table PSDB")  

* DC efeito na direita - Table A.3 - Bottom
rdrobust disp_dc_d_fil_ROB margem_vit if 	d_dir_ctr_ROB==1 & (antes_eleicoes==1) , vce(cluster codigo_ibge) 	p (1) all h (0.145) b (0.247)
outreg2 using TablePSDBAfil, excel label append nonotes title("Table PSDB")  
rdrobust disp_dc_d_fil_ROB margem_vit if 	d_dir_ctr_ROB==1 & (todas_eleicoes==1) , vce(cluster codigo_ibge) 	p (1) all h (0.130) b (0.232)
outreg2 using TablePSDBAfil, excel label append nonotes title("Table PSDB")  
rdrobust disp_dc_d_fil_ROB margem_vit if 	d_dir_ctr_ROB==1 & (doisanos_eleicoes==1) , vce(cluster codigo_ibge) 	p (1) all h (0.165) b (0.257)
outreg2 using TablePSDBAfil, excel label append nonotes title("Table PSDB")  
rdrobust disp_dc_d_fil_ROB margem_vit if 	d_dir_ctr_ROB==1 & (todas_eleicoes==1)  & reeleito == 1, vce(cluster codigo_ibge) 	p (1) all h (0.145) b (0.239)
outreg2 using TablePSDBAfil, excel label append nonotes title("Table PSDB")  
rdrobust disp_dc_d_fil_ROB margem_vit if 	d_dir_ctr_ROB==1 & (todas_eleicoes==1) , vce(cluster codigo_ibge)	p (2) all h (0.199) b (0.300) 
outreg2 using TablePSDBAfil, excel label append nonotes title("Table PSDB")  
rdrobust disp_dc_d_fil_ROB margem_vit if 	d_dir_ctr_ROB==1 & (todas_eleicoes==1)  & reeleito == 1, vce(cluster codigo_ibge)	p (2) all h (0.262) b (0.403) 
outreg2 using TablePSDBAfil, excel label append nonotes title("Table PSDB")  
rdrobust disp_dc_d_fil_ROB margem_vit if 	d_dir_ctr_ROB==1 & (todas_eleicoes==1) , vce(cluster codigo_ibge)	p (1) all h (0.130) b (0.10) 
outreg2 using TablePSDBAfil, excel label append nonotes title("Table PSDB")  
rdrobust disp_dc_d_fil_ROB margem_vit if 	d_dir_ctr_ROB==1 & (todas_eleicoes==1)  & reeleito == 1, vce(cluster codigo_ibge)	p (1) all h (0.145) b (0.10)  
outreg2 using TablePSDBAfil, excel label append nonotes title("Table PSDB")  
rdrobust disp_dc_d_fil_ROB margem_vit if 	d_dir_ctr_ROB==1 & (todas_eleicoes==1) , vce(cluster codigo_ibge)	p (1) all h (0.130) b (0.40) 
outreg2 using TablePSDBAfil, excel label append nonotes title("Table PSDB")  
rdrobust disp_dc_d_fil_ROB margem_vit if 	d_dir_ctr_ROB==1 & (todas_eleicoes==1)  & reeleito == 1, vce(cluster codigo_ibge)	p (1) all h (0.145) b (0.40)  
outreg2 using TablePSDBAfil, excel label append nonotes title("Table PSDB") 

* DE efeito na esquerda - Table A.4 - Top
rdrobust disp_de_e_fil_ROB margem_vit if 	d_dir_esq_ROB==1 & (antes_eleicoes==1) , vce(cluster codigo_ibge) p (1) all h (0.137) b (0.225)
outreg2 using TablePSDBAfil, excel label append nonotes title("Table PSDB")  
rdrobust disp_de_e_fil_ROB margem_vit if 	d_dir_esq_ROB==1 & (todas_eleicoes==1) , vce(cluster codigo_ibge)	p (1) all h (0.146) b (0.302)
outreg2 using TablePSDBAfil, excel label append nonotes title("Table PSDB")  
rdrobust disp_de_e_fil_ROB margem_vit if 	d_dir_esq_ROB==1 & (doisanos_eleicoes==1) , vce(cluster codigo_ibge)	p (1) all h (0.170) b (0.333)
outreg2 using TablePSDBAfil, excel label append nonotes title("Table PSDB")  
rdrobust disp_de_e_fil_ROB margem_vit if 	d_dir_esq_ROB==1 & (todas_eleicoes==1)  & reeleito == 1, vce(cluster codigo_ibge)	p (1) all h (0.242) b (0.433)
outreg2 using TablePSDBAfil, excel label append nonotes title("Table PSDB")  
rdrobust disp_de_e_fil_ROB margem_vit if 	d_dir_esq_ROB==1 & (todas_eleicoes==1) , vce(cluster codigo_ibge)	p (2) all h (0.205) b (0.347) 
outreg2 using TablePSDBAfil, excel label append nonotes title("Table PSDB")  
rdrobust disp_de_e_fil_ROB margem_vit if 	d_dir_esq_ROB==1 & (todas_eleicoes==1)  & reeleito == 1, vce(cluster codigo_ibge)	p (2) all h (0.250) b (0.468) 
outreg2 using TablePSDBAfil, excel label append nonotes title("Table PSDB")  
rdrobust disp_de_e_fil_ROB margem_vit if 	d_dir_esq_ROB==1 & (todas_eleicoes==1) , vce(cluster codigo_ibge)	p (1) all h (0.146) b (0.10) 
outreg2 using TablePSDBAfil, excel label append nonotes title("Table PSDB")  
rdrobust disp_de_e_fil_ROB margem_vit if 	d_dir_esq_ROB==1 & (todas_eleicoes==1)  & reeleito == 1, vce(cluster codigo_ibge)	p (1) all h (0.242) b (0.10)  
outreg2 using TablePSDBAfil, excel label append nonotes title("Table PSDB")  
rdrobust disp_de_e_fil_ROB margem_vit if 	d_dir_esq_ROB==1 & (todas_eleicoes==1) , vce(cluster codigo_ibge)	p (1) all h (0.146) b (0.40) 
outreg2 using TablePSDBAfil, excel label append nonotes title("Table PSDB")  
rdrobust disp_de_e_fil_ROB margem_vit if 	d_dir_esq_ROB==1 & (todas_eleicoes==1)  & reeleito == 1, vce(cluster codigo_ibge)	p (1) all h (0.242) b (0.40)  
outreg2 using TablePSDBAfil, excel label append nonotes title("Table PSDB")  

* EC efeito na esquerda - Table A.4 - Bottom
rdrobust disp_ec_e_fil_ROB margem_vit if 	d_esq_ctr_ROB==1 & (antes_eleicoes==1) , vce(cluster codigo_ibge) 	p (1) all h (0.123) b (0.218)
outreg2 using TablePSDBAfil, excel label append nonotes title("Table PSDB")  
rdrobust disp_ec_e_fil_ROB margem_vit if 	d_esq_ctr_ROB==1 & (todas_eleicoes==1) , vce(cluster codigo_ibge) p (1) all h (0.148) b (0.240)
outreg2 using TablePSDBAfil, excel label append nonotes title("Table PSDB")  
rdrobust disp_ec_e_fil_ROB margem_vit if 	d_esq_ctr_ROB==1 & (doisanos_eleicoes==1) , vce(cluster codigo_ibge) p (1) all h (0.129) b (0.226)
outreg2 using TablePSDBAfil, excel label append nonotes title("Table PSDB")  
rdrobust disp_ec_e_fil_ROB margem_vit if 	d_esq_ctr_ROB==1 & (todas_eleicoes==1)  & reeleito == 1, vce(cluster codigo_ibge) p (1) all h (0.184) b (0.283)
outreg2 using TablePSDBAfil, excel label append nonotes title("Table PSDB")  
rdrobust disp_ec_e_fil_ROB margem_vit if 	d_esq_ctr_ROB==1 & (todas_eleicoes==1) , vce(cluster codigo_ibge)	p (2) all h (0.194) b (0.279) 
outreg2 using TablePSDBAfil, excel label append nonotes title("Table PSDB")  
rdrobust disp_ec_e_fil_ROB margem_vit if 	d_esq_ctr_ROB==1 & (todas_eleicoes==1)  & reeleito == 1, vce(cluster codigo_ibge)	p (2) all h (0.259) b (0.364) 
outreg2 using TablePSDBAfil, excel label append nonotes title("Table PSDB")  
rdrobust disp_ec_e_fil_ROB margem_vit if 	d_esq_ctr_ROB==1 & (todas_eleicoes==1) , vce(cluster codigo_ibge)	p (1) all h (0.148) b (0.10) 
outreg2 using TablePSDBAfil, excel label append nonotes title("Table PSDB")  
rdrobust disp_ec_e_fil_ROB margem_vit if 	d_esq_ctr_ROB==1 & (todas_eleicoes==1)  & reeleito == 1, vce(cluster codigo_ibge)	p (1) all h (0.184) b (0.10)
outreg2 using TablePSDBAfil, excel label append nonotes title("Table PSDB")  
rdrobust disp_ec_e_fil_ROB margem_vit if 	d_esq_ctr_ROB==1 & (todas_eleicoes==1) , vce(cluster codigo_ibge)	p (1) all h (0.148) b (0.40) 
outreg2 using TablePSDBAfil, excel label append nonotes title("Table PSDB")  
rdrobust disp_ec_e_fil_ROB margem_vit if 	d_esq_ctr_ROB==1 & (todas_eleicoes==1)  & reeleito == 1, vce(cluster codigo_ibge)	p (1) all h (0.184) b (0.40)
outreg2 using TablePSDBAfil, excel label append nonotes title("Table PSDB")  

* DC efeito no centro - A.5 - Top
rdrobust disp_dc_c_fil_ROB margem_vit if 	d_dir_ctr_ROB==1 & (antes_eleicoes==1) , vce(cluster codigo_ibge) 	p (1) all h (0.111) b (0.207)
outreg2 using TablePSDBAfil, excel label append nonotes title("Table PSDB")  
rdrobust disp_dc_c_fil_ROB margem_vit if 	d_dir_ctr_ROB==1 & (todas_eleicoes==1) , vce(cluster codigo_ibge) 	p (1) all h (0.173) b (0.292)
outreg2 using TablePSDBAfil, excel label append nonotes title("Table PSDB")  
rdrobust disp_dc_c_fil_ROB margem_vit if 	d_dir_ctr_ROB==1 & (doisanos_eleicoes==1) , vce(cluster codigo_ibge) 	p (1) all h (0.182) b (0.287)
outreg2 using TablePSDBAfil, excel label append nonotes title("Table PSDB")  
rdrobust disp_dc_c_fil_ROB margem_vit if 	d_dir_ctr_ROB==1 & (todas_eleicoes==1)  & reeleito == 1, vce(cluster codigo_ibge) 	p (1) all h (0.171) b (0.272)
outreg2 using TablePSDBAfil, excel label append nonotes title("Table PSDB")  
rdrobust disp_dc_c_fil_ROB margem_vit if 	d_dir_ctr_ROB==1 & (todas_eleicoes==1) , vce(cluster codigo_ibge)	p (2) all h (0.249) b (0.374) 
outreg2 using TablePSDBAfil, excel label append nonotes title("Table PSDB")  
rdrobust disp_dc_c_fil_ROB margem_vit if 	d_dir_ctr_ROB==1 & (todas_eleicoes==1)  & reeleito == 1, vce(cluster codigo_ibge)	p (2) all h (0.303) b (0.455) 
outreg2 using TablePSDBAfil, excel label append nonotes title("Table PSDB")  
rdrobust disp_dc_c_fil_ROB margem_vit if 	d_dir_ctr_ROB==1 & (todas_eleicoes==1) , vce(cluster codigo_ibge)	p (1) all h (0.173) b (0.10) 
outreg2 using TablePSDBAfil, excel label append nonotes title("Table PSDB")  
rdrobust disp_dc_c_fil_ROB margem_vit if 	d_dir_ctr_ROB==1 & (todas_eleicoes==1)  & reeleito == 1, vce(cluster codigo_ibge)	p (1) all h (0.171) b (0.10)  
outreg2 using TablePSDBAfil, excel label append nonotes title("Table PSDB")  
rdrobust disp_dc_c_fil_ROB margem_vit if 	d_dir_ctr_ROB==1 & (todas_eleicoes==1) , vce(cluster codigo_ibge)	p (1) all h (0.173) b (0.40) 
outreg2 using TablePSDBAfil, excel label append nonotes title("Table PSDB")  
rdrobust disp_dc_c_fil_ROB margem_vit if 	d_dir_ctr_ROB==1 & (todas_eleicoes==1)  & reeleito == 1, vce(cluster codigo_ibge)	p (1) all h (0.171) b (0.40)  
outreg2 using TablePSDBAfil, excel label append nonotes title("Table PSDB") 

* EC efeito no centro - Table A.5 - Bottom
rdrobust disp_ec_c_fil_ROB margem_vit if 	d_esq_ctr_ROB==1 & (antes_eleicoes==1) , vce(cluster codigo_ibge) 	p (1) all h (0.132) b (0.208)
outreg2 using TablePSDBAfil, excel label append nonotes title("Table PSDB")  
rdrobust disp_ec_c_fil_ROB margem_vit if 	d_esq_ctr_ROB==1 & (todas_eleicoes==1) , vce(cluster codigo_ibge) p (1) all h (0.179) b (0.307)
outreg2 using TablePSDBAfil, excel label append nonotes title("Table PSDB")  
rdrobust disp_ec_c_fil_ROB margem_vit if 	d_esq_ctr_ROB==1 & (doisanos_eleicoes==1) , vce(cluster codigo_ibge) p (1) all h (0.155) b (0.241)
outreg2 using TablePSDBAfil, excel label append nonotes title("Table PSDB")  
rdrobust disp_ec_c_fil_ROB margem_vit if 	d_esq_ctr_ROB==1 & (todas_eleicoes==1)  & reeleito == 1, vce(cluster codigo_ibge) p (1) all h (0.216) b (0.338)
outreg2 using TablePSDBAfil, excel label append nonotes title("Table PSDB")  
rdrobust disp_ec_c_fil_ROB margem_vit if 	d_esq_ctr_ROB==1 & (todas_eleicoes==1) , vce(cluster codigo_ibge)	p (2) all h (0.210) b (0.300) 
outreg2 using TablePSDBAfil, excel label append nonotes title("Table PSDB")  
rdrobust disp_ec_c_fil_ROB margem_vit if 	d_esq_ctr_ROB==1 & (todas_eleicoes==1)  & reeleito == 1, vce(cluster codigo_ibge)	p (2) all h (0.213) b (0.300) 
outreg2 using TablePSDBAfil, excel label append nonotes title("Table PSDB")  
rdrobust disp_ec_c_fil_ROB margem_vit if 	d_esq_ctr_ROB==1 & (todas_eleicoes==1) , vce(cluster codigo_ibge)	p (1) all h (0.179) b (0.10) 
outreg2 using TablePSDBAfil, excel label append nonotes title("Table PSDB")  
rdrobust disp_ec_c_fil_ROB margem_vit if 	d_esq_ctr_ROB==1 & (todas_eleicoes==1)  & reeleito == 1, vce(cluster codigo_ibge)	p (1) all h (0.216) b (0.10)
outreg2 using TablePSDBAfil, excel label append nonotes title("Table PSDB")  
rdrobust disp_ec_c_fil_ROB margem_vit if 	d_esq_ctr_ROB==1 & (todas_eleicoes==1) , vce(cluster codigo_ibge)	p (1) all h (0.179) b (0.40) 
outreg2 using TablePSDBAfil, excel label append nonotes title("Table PSDB")  
rdrobust disp_ec_c_fil_ROB margem_vit if 	d_esq_ctr_ROB==1 & (todas_eleicoes==1)  & reeleito == 1, vce(cluster codigo_ibge)	p (1) all h (0.216) b (0.40)
outreg2 using TablePSDBAfil, excel label append nonotes title("Table PSDB")  

capture log close
